### ISSUE TITLE
 Missing implementation of resolved method 'abstract com.jetbrains.php.tools.quality.QualityToolType getQualityToolType()'

### ISSUE THREAD

**Issue by adri** [JetBrains/phpstorm-phpstan-plugin#4]
Hi 👋 

I installed the PHPStorm 2020.3 EAP and got the following exception when trying the PHPStan integration. 
Please let me know if you need any more information :) 

```
ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: de.espend.idea.php.quality.phpstan.PhpStanAnnotatorQualityToolAnnotator@55928e4b (class de.espend.idea.php.quality.phpstan.PhpStanAnnotatorQualityToolAnnotator) [Plugin: de.espend.idea.php.generics]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:323)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:59)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:255)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectInformationWithProgress(ExternalToolPass.java:137)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:394)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:393)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:369)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:367)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:185)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract com.jetbrains.php.tools.quality.QualityToolType getQualityToolType()' of abstract class com.jetbrains.php.tools.quality.QualityToolAnnotator.
	at com.jetbrains.php.tools.quality.QualityToolAnnotator.collectAnnotatorInfo(QualityToolAnnotator.java:83)
	at com.jetbrains.php.tools.quality.QualityToolAnnotator.collectInformation(QualityToolAnnotator.java:137)
	at com.jetbrains.php.tools.quality.QualityToolAnnotator.collectInformation(QualityToolAnnotator.java:71)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectInformationWithProgress(ExternalToolPass.java:134)
	... 19 more
```

**Comment by wbars** [comment]
Hello, issue you're experiencing is coming from [another plugin](https://github.com/Haehnchen/idea-php-generics-plugin/issues), please report issue there.

**Comment by adri** [comment]
Hi! Thank you, I’m sorry for my confusion.

**Comment by bzixilu** [comment]
Filed: Plugin is not compatible with PhpStorm 2020.3 #61
